version: "3"
    
services:
  #DISCOVERY SERVICE
  discovery:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    image: df/discovery:0.01
    ports:
      - 8763:8761
    networks:
      - epic-network

      
  #API GATEWAY
  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    image: df/gateway:0.01
    ports:
      - 8081:5256
    environment:
      DISCOVERY_URL: http://discovery:8761
    depends_on:
      - discovery
    networks:
      - epic-network
  
  #AUTH SERVICE
  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: df/auth:0.01
    environment:
      DISCOVERY_URL: http://discovery:8761
    depends_on:
      - discovery
    networks:
      - epic-network

  #ADMIN SERVICE
  #admin:
  #  build:
  #    context: ./admin-service
  #    dockerfile: Dockerfile
  #  image: df/admin:0.01
  #  ports:
  #    - 8383:8383
  #  depends_on:
  #    - discovery
      
  #BROKER SERVICE
  broker:
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    image: df/broker:0.01
    environment:
      DISCOVERY_URL: http://discovery:8761
    depends_on:
      - discovery
    networks:
      - epic-network
      
  #COMMON SERVICE
  common:
    build:
      context: ./common-service
      dockerfile: Dockerfile
    image: df/common:0.01
    environment:
      DISCOVERY_URL: http://discovery:8761
    depends_on:
      - discovery
    networks:
      - epic-network
      
  #FD SERVICE
  fd:
    build:
      context: ./fd-service
      dockerfile: Dockerfile
    image: df/fd:0.01
    environment:
      DISCOVERY_URL: http://discovery:8761
    depends_on:
      - discovery
    networks:
      - epic-network
      
  #Savings Pocket (SP) SERVICE
  #sp:
  #  build:
  #    context: ./sp-service
  #    dockerfile: Dockerfile
  #  image: df/sp:0.01
  #  depends_on:
  #    - discovery

networks:
    epic-network:
      driver: bridge